workdir: "/mnt/Data/Practice/RRBS_Snakemake/wrapper"
pre_trim_qc: "pre_trim_qc"
trimming_folder: "trimmed"
post_trim_qc: "post_trim_qc"
alignment_folder: "mapped"
temp: "temp"
logs_for_mail: "logs_for_mail"