channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - snakemake-minimal >=7.3
  - trimmomatic ==0.39
  - pigz ==2.6
  - snakemake-wrapper-utils ==0.5.3
  - pygments
  - pandas ==1.5.3
